---
title: "IC-7610"
author: "Rick Gilmore K3ROG"
date: "`r Sys.time()`"
output: html_document
---

## IC-7610

### Equipment summary

- Icom IC-7610 (HF + 6m)
    - Astron power supply
- Elecraft KPA1500
  - Elecraft power supply
- Windows 10 PC, dual monitor set-up
  - WSTJ-X, JS8Call, fldigi, N1MM, N3FJP
- The default configuration uses the ICOM SM-50 desk mic.
- There is a Clipper footswitch for the PTT on the floor.
- There is a Heil headset.
- We have a Nifty Mini-manual and other manuals are located in the drawer under the radio.

### Connect equipment and power-up

- The IC-7610 is located closest to the door.
- Connect the equipment to the power mains.
    - Plug the large 240 V cable for the amplifier into the 240 V wall outlet.
    - Plug the smaller 120 V cable for the Uninterrupted Power Supply (UPS) into the wall outlet.
- Power up the UPS by pushing the front button.
    - If needed, power up the PC.
- Power up the Astron RS-35A power supply that powers the IC-7610. The power supply is located to the right of the Elecraft KPA1500 amplifier.
- Before you power up the radio, connect it to a suitable antenna.
    - The antenna connections are located on the north wall, near the repeater cabinet.
    - Plug the cable from the radio (yellow tag) into the cable connector for one of the antennas, for example, one of the triband Yagi's for 10 - 20 m.
- Power up the IC-7610 by pressing and briefly holding the power button.
- The IC-7610 is connected to the Elecraft KPA1500 amplifier. The power supply for the KPA1500 is under the desk on a small footstool. Check that the KPA1500 power supply is on. If necessary, power-up the power supply by hitting the power switch on the upper rear left side of the power supply.
- Power up the KPA1500 by pressing the on switch on the lower right hand side of the KPA1500.

#### Log-in to the computer

- The IC-7610 is connected via USB to the NARC-1 PC.
- Open your logging program of choice. NARC has licenses for N1MM and N3FJP's Amateur Contact Log.
- To operate digital modes (e.g., FT8/FT4, JS8Call, fldigi), open those programs. See instructions for operating these modes below.

### Accessories

- The default configuration uses the ICOM SM-50 desk mic.
- There is a Clipper footswitch for the PTT on the floor.
- There is a Heil headset.
- We have a Nifty Mini-manual and other manuals are located in the drawer under the radio.
