project:
  type: book
  output-dir: ../docs

book:
  title: "Nittany ARC Station Guide"
  author: "Rick Gilmore"
  date: "2023-11-23"
  chapters:
    - index.qmd
    - logistics.qmd
    - antennas.qmd
    - "IC-7610.qmd"
    - "wifi-internet.qmd"
    - packet_aprs.qmd

format:
  html:
    theme: cosmo
    number-sections: false
    