---
title: "Preface"
---

## About

Welcome to the Nittany Amateur Radio Club's ([NARC](https://nittany-arc.org)) station guide.
The radio station is one of the best benefits of joining the club.

Rick Gilmore, W3TM manages the station with the help of Mike Coslo N3LI, Eric Prescott W3EDP, and Woody Brem K3YV.
Mark Wharton K0LO provides computer networking support.

This site provides information about how to gain access to the mountaintop station and how to use the equipment.

The mountaintop station has been a focal point of activity for the club.
We operated Field Day 2023 from the station, and we have held W3M special event operations, Pennsylvania QSO Party activities, and other contesting events.

## Stations

The club maintains two full power HF + 6m stations ([NARC-1](narc1.qmd) and [NARC-2](narc2.qmd)), plus a 100 W HF + 6m station ([NARC-3](narc3.qmd)).
In addition, the mountaintop radio station has a dual band VHF/UHF FM radio for monitoring the 146.86 MHz W3YA and 146.76 MHz W3GA repeaters.
We have a [packet station](packet_aprs.qmd#packet-station) and bulletin board operating on 145.030 MHz, and the club supports a full-time [APRS digipeater](packet_aprs.qmd#aprs-station) active on 144.390 MHz as W3YA-1.
