on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
      
jobs:
  build-website:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Render Quarto Project
          uses: quarto-dev/quarto-actions/render@v2
          path: src # By default, the current working dir is used i.e `quarto render .`